// LOGIN Actions
export const SET_ACCESS_ID = 'SET_ACCESS_ID';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const LOGIN_SUCCESS = 'LOGIN';

// LIST Actions
export const SET_LISTS = 'SET_LISTS'
export const SWITCH_SHOW_ADD_LIST_FORM = 'SWITCH_SHOW_ADD_LIST_FORM'
export const SET_CREATE_LIST_NAME = 'SET_CREATE_LIST_NAME'
export const SET_CREATE_LIST_DESCRIPTION = 'SET_CREATE_LIST_DESCRIPTION'

// TASK Actions
export const SET_TASKS = 'SET_TASKS'
export const SET_TASKS_LIST_NAME = 'SET_TASKS_LIST_NAME'
export const SET_TASKS_LIST_ID = 'SET_TASKS_LIST_ID'
export const SWITCH_SHOW_ADD_TASK_FORM = 'SWITCH_SHOW_ADD_TASK_FORM'
export const SET_CREATE_TASK_NAME = 'SET_CREATE_TASK_NAME'
export const SET_CREATE_TASK_DESCRIPTION = 'SET_CREATE_TASK_DESCRIPTION'
export const SWITCH_SET_TASK_IS_DONE = 'SWITCH_SET_TASK_IS_DONE'